
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Luzza
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Dashboard() {
        initComponents();
    }

    public Dashboard(String role) {
        initComponents();
        //System.out.println(role);
        setLocationRelativeTo(null);
        if (role.equals("Admin")) {
            btnUser.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUser = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnViewOrder = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        userLbl = new javax.swing.JLabel();
        noofuserLbl = new javax.swing.JLabel();
        totalcategoryLbl = new javax.swing.JLabel();
        noofcategoryLbl = new javax.swing.JLabel();
        totalproductLbl = new javax.swing.JLabel();
        noofproductLbl = new javax.swing.JLabel();
        weeklysalestotalamountLbl = new javax.swing.JLabel();
        totalamountLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lowstockTbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recentlyAddedTbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUser.setBackground(new java.awt.Color(255, 255, 255));
        btnUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users.png"))); // NOI18N
        btnUser.setText("User");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 70));

        btnCategory.setBackground(new java.awt.Color(255, 255, 255));
        btnCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        btnCategory.setText("Category");
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 230, 70));

        btnProduct.setBackground(new java.awt.Color(255, 255, 255));
        btnProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product.png"))); // NOI18N
        btnProduct.setText("Prodcut");
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 70));

        btnCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customers.png"))); // NOI18N
        btnCustomer.setText("Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 230, 70));

        btnOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Orders.png"))); // NOI18N
        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 230, 70));

        btnViewOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnViewOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View-orders.png"))); // NOI18N
        btnViewOrder.setText("View Order");
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 230, 70));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 606, 230, 70));

        userLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        userLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users.png"))); // NOI18N
        userLbl.setText("Total User");
        getContentPane().add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        noofuserLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        getContentPane().add(noofuserLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 60, 40));

        totalcategoryLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        totalcategoryLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        totalcategoryLbl.setText("Total Category");
        getContentPane().add(totalcategoryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        noofcategoryLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        getContentPane().add(noofcategoryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 70, 40));

        totalproductLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        totalproductLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product.png"))); // NOI18N
        totalproductLbl.setText("Total Products");
        getContentPane().add(totalproductLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, -1));

        noofproductLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        getContentPane().add(noofproductLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 70, 40));

        weeklysalestotalamountLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        weeklysalestotalamountLbl.setText("Weekly Sales Total Amount");
        getContentPane().add(weeklysalestotalamountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 100, -1, 40));

        totalamountLbl.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        getContentPane().add(totalamountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 100, 70, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 9, 699));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 138, 1070, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Low Stock Products");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 159, -1, -1));

        lowstockTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(lowstockTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 525, 464));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Recently Added Products");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, -1));

        recentlyAddedTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price", "Description"
            }
        ));
        jScrollPane2.setViewportView(recentlyAddedTbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 540, 464));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        new ManageCustomer().setVisible(true);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int temp = JOptionPane.showConfirmDialog(null, "Do you want to logout application", "Select", JOptionPane.YES_NO_OPTION);
        if (temp == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        new ManageUser().setVisible(true);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        // TODO add your handling code here:
        new ManageProduct().setVisible(true);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        new ManageOrder().setVisible(true);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:
        new ViewOrders().setVisible(true);
    }//GEN-LAST:event_btnViewOrderActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            int countUser = 0;
            int countCategory = 0;
            int countProduct = 0;
            int sales = 0;
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            //count user, category, product
            ResultSet rs1 = st.executeQuery("SELECT * FROM appuser");
            while (rs1.next()) {
                countUser++;
            }
            ResultSet rs2 = st.executeQuery("SELECT * FROM category");
            while (rs2.next()) {
                countCategory++;
            }
            ResultSet rs3 = st.executeQuery("SELECT quantity FROM product");
            while (rs3.next()) {
                int quantity = Integer.parseInt(rs3.getString("quantity"));
                countProduct += quantity;
            }
            
            //weekly sales
            Calendar cal = Calendar.getInstance();
            int currentWeek = cal.get(Calendar.WEEK_OF_YEAR);

            String query = "SELECT week, SUM(total_sales) AS total_sales "
                    + "FROM (SELECT WEEKOFYEAR(STR_TO_DATE(orderDate, '%d-%m-%Y')) AS week, totalPaid AS total_sales "
                    + "FROM orderdetail "
                    + "WHERE WEEKOFYEAR(STR_TO_DATE(orderDate, '%d-%m-%Y')) = " + currentWeek + ") AS subquery "
                    + "GROUP BY week";

            ResultSet rs4 = st.executeQuery(query);

            if (rs4.next()) {
                sales = rs4.getInt("total_sales");
                System.out.println("Total sales for current week: " + sales);
            } else {
                System.out.println("No sales data found for the current week.");
            }
            
            //low quantity product
            DefaultTableModel model1 = (DefaultTableModel) lowstockTbl.getModel();
            ResultSet rs5 = st.executeQuery("SELECT * FROM product");
            while (rs5.next()) {
                int quantity = rs5.getInt("quantity");
                if (quantity <= 30) {
                    model1.addRow(new Object[]{rs5.getInt("product_pk"), rs5.getString("name"), rs5.getInt("quantity")});
                }
            }
            
            //recently added product
            DefaultTableModel model2 = (DefaultTableModel) recentlyAddedTbl.getModel();
            ResultSet rs6 = st.executeQuery("SELECT * FROM product ORDER BY product_pk DESC LIMIT 5");
            while (rs6.next()) {
                model2.addRow(new Object[]{rs6.getString("name"), rs6.getInt("quantity"), rs6.getInt("price"),rs6.getString("description")});   
            }
            
            //view mathi ko sabai kura
            noofuserLbl.setText("" + countUser);
            noofcategoryLbl.setText("" + countCategory);
            noofproductLbl.setText("" + countProduct);
            totalamountLbl.setText("" + sales);
        } catch (Exception e) {
            System.out.println(e);
            //JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//         try {
//            UIManager.setLookAndFeel("javax.swing.plaf.graphite.GraphiteBorderFactory");
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
//            e.printStackTrace();
//        }
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable lowstockTbl;
    private javax.swing.JLabel noofcategoryLbl;
    private javax.swing.JLabel noofproductLbl;
    private javax.swing.JLabel noofuserLbl;
    private javax.swing.JTable recentlyAddedTbl;
    private javax.swing.JLabel totalamountLbl;
    private javax.swing.JLabel totalcategoryLbl;
    private javax.swing.JLabel totalproductLbl;
    private javax.swing.JLabel userLbl;
    private javax.swing.JLabel weeklysalestotalamountLbl;
    // End of variables declaration//GEN-END:variables
}
